name: agropilot
description: Переработка проекта САР

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter


  # Core & Architecture
  equatable: ^2.0.7
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  fpdart: ^1.1.1

  # Navigation
  auto_route: ^10.1.0+1

  # Connectivity
  usb_serial: ^0.5.1                # юсб
  flutter_blue_plus: ^1.35.5       # блютуз

  # Storage
  shared_preferences: ^2.5.3
  objectbox: ^4.3.0
  objectbox_flutter_libs: any

  # UI & Utils
  permission_handler: ^12.0.0+1     # разрешения устройств
  uuid: ^4.5.1
  #  path_provider: ^2.1.2             # пути устройства
  #  circular_seek_bar: ^1.1.1         # индикатор
  #  flutter_map: ^8.1.1               # карта
  #  flutter_map_animations: ^0.9.0    # анимирование маркеров на карте
  #  flutter_map_animated_marker: ^2.0.0
  #  latlong2: ^0.9.1                  # координаты на карте

  #  vector_math: ^2.1.4               # векторные математические вычисления
  #  jiffy: ^6.2.2                     # форматирование времени
  #  quiver: ^3.2.1
  #  collection: ^1.18.0
  #  freezed: ^3.0.6
  #  clipper2: ^0.0.3

  #  polybool: ^0.2.0 # логические операции над полигонами
  # dart run build_runner build
  # flutter run build_runner build



dev_dependencies:
  flutter_test:
    sdk: flutter

  #  injectable_generator: ^2.7.0
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  objectbox_generator: any
  auto_route_generator: ^10.2.3

flutter:
  uses-material-design: true
#  assets:
#    - assets/translations/
#    - assets/icons/

flutter_gen:
  output: lib/generated/